import Navbar from "components/navbar/Navbar";
import WithPadding from "components/shared/WithPadding";
import style from "./PrivacyPolicy.module.scss";

export default function PrivacyPolicy() {
  return (
    <div className={style.wrapper}>
      <Navbar background="white" />

      <WithPadding>
        <div className={style.title}>Privacy Policy</div>

        <div class="container">
          <div class="row terms-condition-section">
            <div class="col-xs-12 about-text">
              <div class="about-text-wrapper">
                <h2 class="home-section-sub-text m-t-30">Introduction</h2>
                <p class="description-sm m-t-40 lh-30">
                  When you use www.hikewise.com, you trust us with your
                  information. We are committed to keeping that trust. That
                  starts with helping you understand our privacy practices. This
                  Privacy Policy is meant to help you understand what data we
                  collect, why we collect it, and what we do with it. This is
                  important; we hope you will take time to read it carefully..
                </p>
                <p class="description-sm lh-30">
                  This document is an electronic record in terms of Information
                  Technology Act, 2000 ("Act") and made thereunder as applicable
                  and the amended provisions pertaining to electronic records in
                  various statutes as amended by the Information Technology
                  (Amendment) Act, 2008. This user agreement is generated by a
                  computer system and does not require any physical or digital
                  signatures.
                </p>
                <p class="description-sm lh-30">
                  This document is published in accordance with the provisions
                  of Rule 3 (1) of the Information Technology (Intermediaries
                  Guidelines) Rules, 2011 that require publishing the rules and
                  regulations, privacy policy and terms and conditions for
                  access and/or usage of www.hikewise.com ("Website").
                </p>
              </div>
              <div class="about-text-wrapper">
                <h2 class="home-section-sub-text m-t-30">
                  What personal information about users does hikewise.com
                  gather?
                </h2>
                <p class="description-sm m-t-40 lh-30"></p>
                <h2 class="home-section-sub-text m-t-30">
                  Information You Give Us
                </h2>
                <p></p>
                <p class="description-sm m-t-40 lh-30">
                  Registration at hikewise.com require user/s to share their
                  personal details including but not limited to name, father's
                  name, phone number, address, e-mail address, school and other
                  academic information, which may be used by vLEAD Eduventures
                  to arrive at a proper psychometric assessment. Although
                  certain information are mandatory, some are not so and you can
                  choose not to provide those.
                </p>

                <p class="description-sm m-t-40 lh-30"></p>
                <h2 class="home-section-sub-text m-t-30">
                  Automatic Information
                </h2>
                <p></p>
                <p class="description-sm m-t-40 lh-30">
                  We receive and store certain types of information whenever you
                  interact with us, as part of standard operation of the site.
                  These include, but not limited to your browser type, operating
                  system, IP address, date and time you visit the site, the
                  areas or pages of the site that you visit, the amount of time
                  you spend viewing the site, the number of times you return to
                  the site, your location and other click-streaular and plural
                  form of the terms. Whenever the context may require, any
                  pronoun shall include both the corresponding masculine and
                  feminine form. The terms as defined herein shall also read as
                  such in the Privacy Policy as well as the Disclaimer of the
                  Website.
                </p>

                <h2 class="home-section-sub-text m-t-30">
                  What about Cookies?
                </h2>
                <p class="description-sm m-t-40 lh-30">
                  We use cookies to collect the non-personal information
                  described above. Cookies are unique identifiers that we
                  transfer to your device and are stored in the hard drive of
                  your computer which will enable our systems to recognize your
                  device and provide you certain features. You are free to
                  decline cookies. But by doing so, you may not be able to use
                  certain features on the site or take full advantage of all of
                  our offerings. Check “Help” menu of your browser to learn how
                  to change your cookie preference. .
                </p>

                <h2 class="home-section-sub-text m-t-30">
                  What about accessing hikewise.com through my Facebook/Google
                  account?
                </h2>
                <p class="description-sm m-t-40 lh-30">
                  vLEAD Eduventures also provides access to hikewise.com to you
                  through your respective Google/Facebook accounts; or as the
                  case may be, during which process your personal or any other
                  information may be shared with vLEAD Eduventures, which may be
                  used by vLEAD Eduventures in terms of the Privacy Policy.
                  Further, irrespective of the mode of your login to the Website
                  you shall remain bound by EULA/Privacy Policy and disclaimer
                  of vLEAD Eduventures.
                </p>

                <h2 class="home-section-sub-text m-t-30">
                  How do you use the information so collected?
                </h2>
                <p class="description-sm m-t-40 lh-30">
                  vLEAD Eduventures shall have the right to use your information
                  you provided us and such usage of your information by us does
                  not amount to violation of any rights you might have in your
                  information.
                </p>
                <p class="description-sm m-t-40 lh-30">
                  We may collect and use your information to
                </p>
                <ul>
                  <li>
                    <p class="description-sm m-t-40 lh-30">
                      Fulfill your request for products and services;
                    </p>
                  </li>
                  <li>
                    <p class="description-sm m-t-40 lh-30">
                      Provide you with targeted offers, site content and
                      advertising on the website;
                    </p>
                  </li>
                  <li>
                    <p class="description-sm m-t-40 lh-30">
                      Contact you with information and promotional materials and
                      offers from our company, contact you when necessary;
                    </p>
                  </li>
                  <li>
                    <p class="description-sm m-t-40 lh-30">
                      Address problems with the site, our business or our
                      products and services and
                    </p>
                  </li>
                  <li>
                    <p class="description-sm m-t-40 lh-30">
                      To protect the security or integrity of the site and our
                      business.
                    </p>
                  </li>
                </ul>
                <h2 class="home-section-sub-text m-t-30">
                  Does hikewise.com share the information so collected?
                </h2>
                <p class="description-sm m-t-40 lh-30">
                  We will not sell, share, or otherwise distribute your Personal
                  Data to third parties except as provided in this Privacy
                  Policy. We may disclose your Personal Data to our affiliates
                  worldwide that agree to treat it in accordance with this
                  Privacy Policy. Personal Data may also be transferred to third
                  parties who act for or on our behalf, for further processing
                  in accordance with the purpose(s) for which the data were
                  originally collected or may otherwise be lawfully processed,
                  such as services delivery, evaluating the usefulness of this
                  website, marketing, data management or technical support as
                  described above. These third parties have contracted with us
                  to only use Personal Data for the agreed upon purpose, and not
                  to sell your Personal Information to third parties, and not to
                  disclose it to third parties except as may be required by law,
                  as permitted by us or as stated in this Privacy Policy.
                </p>
                <p class="description-sm m-t-40 lh-30">
                  Personal Data collected from you may also be transferred to a
                  third party in the event that the business of this site or a
                  part of it and the customer data connected with it is sold,
                  assigned or transferred, in which case we would require the
                  buyer, assignee or transferee to treat Personal Data in
                  accordance with this Privacy Policy. Also, Personal Data may
                  be disclosed to a third party if we are required to do so
                  because of an applicable law, court order or governmental
                  regulation, or if such disclosure is otherwise necessary in
                  support of any criminal or other legal investigation or
                  proceeding here or abroad.
                </p>
                <h2 class="home-section-sub-text m-t-30">
                  How Secure Is Information About Me?
                </h2>
                <p class="description-sm m-t-40 lh-30">
                  The security of personal information you have provided us is
                  of paramount importance to us. When you enter sensitive
                  information, such as login credentials and payment regarding
                  information, we encrypt the transmission of that information
                  using secure socket layer technology (SSL).
                </p>
                <p class="description-sm m-t-40 lh-30">
                  We follow generally accepted standards to protect the personal
                  information submitted to us, both during transmission and once
                  we receive it. However, no method of transmission over the
                  Internet, or method of electronic storage, is 100% secure.
                  Therefore, we cannot guarantee its absolute security.
                </p>
                <h2 class="home-section-sub-text m-t-30">
                  Regarding changes in the privacy policy
                </h2>
                <p class="description-sm m-t-40 lh-30 m-b-160">
                  Our Privacy Policy may change from time to time. We will not
                  reduce your rights under this Privacy Policy without your
                  explicit consent. We will post any privacy policy changes on
                  this page and, if the changes are significant, we will provide
                  a more prominent notice (including, for certain services,
                  email notification of privacy policy changes). We will also
                  keep prior versions of this Privacy Policy in an archive for
                  your review.
                </p>
              </div>
            </div>
          </div>
        </div>
      </WithPadding>
    </div>
  );
}
