import Footer from "components/footer/Footer";
import Navbar from "components/navbar/Navbar";
import WithPadding from "components/shared/WithPadding";
import style from "./TermsAndConditions.module.scss";

export default function TermsAndConditions() {
  return (
    <div className={style.wrapper}>
      <Navbar background="white" />

      <WithPadding>
        <div className={style.title}>Terms & Conditions</div>

        <div className="container">
          <div className="row terms-condition-section">
            <div className="col-xs-12 about-text">
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Introduction</h2>
                <p className="description-sm m-t-40 lh-30">
                  This user agreement is an electronic record in terms of
                  Information Technology Act, 2000 ("Act") and made thereunder
                  as applicable and the amended provisions pertaining to
                  electronic records in various statutes as amended by the
                  Information Technology (Amendment) Act, 2008. This user
                  agreement is generated by a computer system and does not
                  require any physical or digital signatures.
                </p>
                <p className="description-sm lh-30">
                  This user agreement is published in accordance with the
                  provisions of Rule 3 (1) of the Information Technology
                  (Intermediaries Guidelines) Rules, 2011 that require
                  publishing the rules and regulations, privacy policy and terms
                  and conditions for access and/or usage of www.hikewise.com
                  ("Website").
                </p>
                <p className="description-sm lh-30">
                  www.hikewise.com, is a technology enabled career assessment
                  test that is aimed at giving a user a deep insight into their
                  psychometric profile and thereby allowing them to take an
                  informed decision/choice at the very right time. The website
                  is managed by vLEAD Management Consultancy Private Limited
                  (CIN: U74999KL2017PTC051485). Before using our services/
                  products you should go through the present Agreement (herein
                  after referred to as EULA) and agree to the terms and
                  conditions of the EULA. The User of the site shall be deemed
                  to have read the terms of the EULA and duly accepted them
                  before browsing through the website.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Reference of terms
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  Except as may otherwise be defined herein, the following terms
                  are defined for the purposes of this EULA.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The term ‘Hikewise’ is used through this entire EULA to refer
                  to the Website, its owner, directors, employees, and
                  individuals / entities associated with the Owner. Owner refers
                  to vLEAD Management Consultancy Private Limited (CIN:
                  74999KL2017PTC051485).
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The term ‘user’ or ‘you’ or ‘your’ is used through this entire
                  EULA to refer to any person who accesses the website or who
                  is/are registered at the website for various services provided
                  by it (User would include individual/legal
                  entity/society/group of people etc. or as the case may be).
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The term ‘our website ‘or just ‘website’ is used through this
                  entire EULA to refer to the Website www.hikewise.com.
                </p>

                <p className="description-sm m-t-40 lh-30">
                  The term ‘Our Product or Services’ is used through this entire
                  EULA to refer to the products/services offered at the Website
                  or its associated entities.
                </p>

                <p className="description-sm m-t-40 lh-30">
                  “Feedback" means any comments or other feedback the customer
                  may provide to Hikewise concerning the functionality and
                  performance of the Licensed Products, including identification
                  of potential errors and improvements.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The terms and conditions herein shall apply equally to both
                  the singular and plural form of the terms. Whenever the
                  context may require, any pronoun shall include both the
                  corresponding masculine and feminine form. The terms as
                  defined herein shall also read as such in the Privacy Policy
                  as well as the Disclaimer of the Website.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Description of services
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise Career Assessment Test is a career assessment test
                  that is aimed at giving a student a deep insight into their
                  psychometric profile and thereby allowing them to take an
                  informed decision/choice at the very right time. It is based
                  on an extensive scientific framework that has been formulated
                  after closely observing the various advancements in the field
                  of psychometrics. Hikewise is offered in three different
                  categories. Hikewise Rise for 8th/ 9th standard students,
                  which suggests the two most suitable streams that they can
                  pursue after their 10th standard. Hikewise Sail for
                  10th/11th/12th standard students and Hikewise Redesign for
                  college students, which suggests the five career fields that
                  are the most congruent to their psychometric profile.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Registration obligation
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  If you register on our website, you shall be responsible for
                  maintaining the confidentiality of your User ID and Password
                  and you shall be responsible for all activities that occur
                  under your User ID and Password.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You agree, inter-alia, to;
                </p>

                <ul>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Provide true, accurate, current and complete information
                      about yourself as prompted by our website registration
                      form (both personal and professional information),
                      maintain and promptly update the Registration Data to keep
                      it true, accurate, current, and complete at all times;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Immediately notify us of any unauthorized use of your
                      password or account or any other breach of security, and;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Ensure that you exit from your account at the end of each
                      session.
                    </p>
                  </li>
                </ul>
                <p className="description-sm m-t-40 lh-30">
                  You agree that if You provide any information that is untrue,
                  inaccurate, not current or incomplete or We have reasonable
                  grounds to suspect that such information is untrue,
                  inaccurate, not current or incomplete, or not in accordance
                  with this Terms of Use, We shall have the right to
                  indefinitely suspend or terminate or block access of your
                  membership on the Website and refuse to provide You with
                  access to the Website. Such an act on your part can accrue
                  legal implications due to violation of laws not limited to
                  criminal liability on your part.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise shall not be liable for any loss or damage arising
                  from your failure to comply with this Clause.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Website license
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  We will be granting you a limited non-exclusive,
                  non-transferable, non-assignable, non-sub-licensable,
                  revocable license, subject to your compliance with this EULA,
                  for the use of the Website.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You acknowledge that Hikewise has no obligation to monitor
                  your access to or use of the Website, Service or Collective
                  Content or to review or edit any Collective Content, but has
                  the right to do so for the purpose of operating the Website,
                  to ensure your compliance with these User Terms or to comply
                  with the applicable law or the order or requirement of a
                  court, administrative agency or other governmental body.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise reserves the right, at any time and without prior
                  notice, to remove or disable access to any Collective Content
                  that we, at our sole discretion, consider to be in violation
                  of these User Terms or otherwise harmful to the Service or
                  Website.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Conditions for use of website
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  In accordance with the Information Technology (Intermediaries
                  guidelines) Rules, 2011, we inform you that
                </p>
                <ul>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      in case of non-compliance with the rules and regulations
                      or EULA or privacy policy for access or usage of our
                      computer resource, or
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      in case if you post or transmit any content which Hikewise
                      believes is not in accordance with this EULA (including
                      materials which infringe or may infringe third party
                      intellectual property rights, rights of privacy or
                      personality rights), or is otherwise unacceptable to
                      Hikewise
                    </p>
                  </li>
                </ul>
                <p className="description-sm m-t-40 lh-30">
                  we reserve the right at our sole discretion to immediately
                  terminate the access or usage rights of the users to our
                  computer resources and block or remove(in whole or in part)
                  the noncompliant information posted or transmitted by you.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You warrant that the information you provide to Hikewise is
                  accurate and complete. We are entitled at all times to verify
                  the information that you have provided us and to refuse the
                  Service or use of the website, partially or completely, at our
                  sole discretion, without providing any reasons, at any time.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You may only access the Services using authorized means.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  In terms of Information Technology (Intermediaries guidelines)
                  Rules 2011, you agree and undertake that you shall not host,
                  display, upload, modify, publish, transmit, update or share
                  any information or share/list(s) any information or item that:
                </p>
                <ul style={{ listStyleType: "circle" }}>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Belongs to the another person and to which You do not have
                      any right ;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Is grossly harmful, harassing, blasphemous, defamatory,
                      obscene, pornographic, paedophilic, libellous, invasive of
                      another’s privacy, hateful or racially/ ethically
                      objectionable, disparaging, relating or encouraging money
                      laundering or gambling or otherwise unlawful in any manner
                      whatsoever; or unlawfully threatening or unlawfully
                      harassing including but not limited to “indecent
                      representation of women” within the meaning of the
                      Indecent Representation of Women ( Prohibition) Act,1986;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Harm minors in any way;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Infringes any patent, trademark, copyright or other
                      proprietary rights or third party’s trade secrets or right
                      of publicity or privacy or is fraudulent or involves the
                      sale of counterfeit or stolen items;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Involves the transmission of “junk mails”, “chain
                      letters”, or unsolicited mask mailing or “spamming”;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Violates any law for the time being in force;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Deceives or misleads addressee/users about the origin of
                      such messages or communicates any information which is
                      grossly offensive or menacing in nature;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Impersonate another person;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Contains software viruses or any other computer code, file
                      or programs designed to interrupt, destroy or limit the
                      functionality of any computer resources;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Threatens the unity, integrity, defence, security or
                      sovereignty of India, friendly relations with foreign
                      states, or public order or causes incitement to the
                      commission of any cognizable offence or prevents
                      investigation of any offence or is insulting any other
                      nation;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Is false, inaccurate or misleading.
                    </p>
                  </li>
                </ul>
                <p className="description-sm m-t-40 lh-30">
                  You agree to promptly notify Hikewise in writing of any user
                  content which breaches these User Terms. You agree to provide
                  us sufficient information to enable us to investigate whether
                  such User Content breaches the terms of EULA. Hikewise agrees
                  to make good faith efforts to investigate such a complaint and
                  shall take such notice as we in our sole discretion decide.
                  However, Hikewise does not warrant or represent that it will
                  block or remove (in whole or in part) such user Content.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Property rights
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  You agree and acknowledge that Hikewise (or its licensors) own
                  all legal right, title and interest in and to the Website and
                  Services and any suggestions, ideas, enhancement requests,
                  feedback, recommendations or other information provided by you
                  or any other party relating to the Website or the Service
                  including any intellectual property rights which subsist in
                  the Services (whether those rights happen to be registered or
                  not, and wherever in the world those rights may exist). You
                  further acknowledge that the Services may contain information
                  which is designated confidential by Hikewise and that you
                  shall not disclose such information without Hikewise’s prior
                  written consent.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You agree that you shall not modify, copy, adapt ,distribute,
                  frame, reproduce, republish, download, scrape, transmit,
                  display, stream, broadcast, or sell in any form or by any
                  means, in whole or in part, or otherwise exploit the Service
                  Materials without Hikewise’s express prior written permission.
                  All other uses of copyrighted material, including but not
                  limited to any derivative use and use of collective contents,
                  require express prior written permission from Hikewise. Any
                  reproduction or redistribution of Service Materials not in
                  accordance with these Terms is expressly prohibited and may
                  result in severe civil and criminal penalties.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Unless you have agreed otherwise in writing with Hikewise,
                  nothing in the Terms gives you a right to use any of
                  Hikewise’s trade names, trademarks, service marks, logos,
                  domain names, and other distinctive brand features.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You acknowledge that this EULA does not constitute a sale and
                  you do not acquire any license or ownership rights by
                  implication or otherwise by using the Service or by accessing
                  any Service Materials posted on the Service by Hikewise. All
                  rights not expressly granted by these Terms are reserved by
                  Hikewise and its licensors, and no license is granted
                  hereunder by estoppel, implication or otherwise, except the
                  limited non-exclusive, non-transferable license granted to you
                  by Hikewise for the use of the Website in this Agreement.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  General prohibitions
                </h2>
                <p className="description-sm m-t-40 lh-30">You may not,</p>
                <ul>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      License, sub license, sell, resell, transfer, assign,
                      distribute or otherwise commercially exploit or make
                      available to any third party the Service or Website in any
                      way;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Modify or make derivative works based upon the Service or
                      Website;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Create internet “links” to the Service or “frame” or
                      “mirror” any Website or any other server or wireless or
                      Internet – based device;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Reverse engineer or access the Website in order to:
                    </p>
                    <ul>
                      <li>
                        <p className="description-sm m-t-40 lh-30">
                          Design or build a competitive product or service,
                        </p>
                      </li>
                      <li>
                        <p className="description-sm m-t-40 lh-30">
                          Design or build a product using similar ideas,
                          features, functions, or graphics of the Service or
                          Website or
                        </p>
                      </li>
                      <li>
                        <p className="description-sm m-t-40 lh-30">
                          Copy any ideas, features, functions or graphics of the
                          Service or Website.
                        </p>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Use any robot, spider, site search/retrieval application,
                      or other manual or automatic device or process to
                      retrieve, index, "data mine", or in any way reproduce or
                      circumvent the navigational structure or presentation of
                      the Website or its contents;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Launch an automated program or script, including, but not
                      limited to, web spiders, web crawlers, web robots, web
                      ants, web indexers, bots, viruses or worms or any program
                      which may make multiple server requests per second, or
                      unduly burdens or hinders the operation and/or performance
                      of the Website;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Post, distribute or reproduce in any way any copyrighted
                      material, trademarks, or other proprietary information
                      without obtaining the prior consent of the owner of the
                      proprietary rights;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Remove any copyright, trademark or other proprietary
                      rights notices contained in the Website
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Send spam or otherwise duplicative or unsolicited messages
                      in violation of applicable laws;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Send or store infringing, obscene, threatening, libellous,
                      or otherwise unlawful or tortuous material, including
                      material harmful to children or that violates the third
                      party privacy rights;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Attempt to gain unauthorized access to the website;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Interfere with or disrupt the integrity or the performance
                      of the Website, or Service or the data contained therein;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Authorize others to use your account;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Assign or otherwise transfer your account to any other
                      person or legal entity;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Use an account that is subject to any rights of a person
                      other than you without appropriate authorization;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Use the Service or Website for unlawful purposes,
                      including but not limited to sending or storing any
                      unlawful material or for fraudulent purposes;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30"></p>
                    Refuse to provide us with whatever proof of identity we may
                    reasonably request;
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Refuse to comply with all the applicable laws from your
                      home nation, the country, state and/or city in which you
                      are present while using the Website or the Service.
                    </p>
                  </li>
                </ul>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise will have the right to investigate and prosecute
                  violations of any of the above to the fullest extent of the
                  law. Hikewise may involve and cooperate with law enforcement
                  authorities in prosecuting users who violate these User Terms.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Consequences of breach of terms
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  Without limiting other remedies that Hikewise may pursue, we
                  may at our sole discretion take such action as it deems fit
                  including but not limited to limit your activity, immediately
                  remove your information, warn other users of your actions,
                  forthwith temporarily/indefinitely suspend or terminate or
                  block your subscription, and/or refuse to provide you with
                  access to the Website or initiate any legal action it may deem
                  fit, particularly in the event:
                </p>
                <ul>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      You breach any of the provisions of this User Agreement
                      including any of the rules and policies, documents, terms
                      and conditions made there under which are incorporated
                      therein by reference;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Failure of verification or authentication of any
                      information provided by you;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      If we believe that your actions may cause legal liability
                      for you, other users or us.
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      If you fail to immediately rectify such breach upon
                      receiving written notice thereof from us.
                    </p>
                  </li>
                </ul>
                <p className="description-sm m-t-40 lh-30">
                  No actions, omissions or decisions taken by the Company shall
                  waive any rights or claims that the Company may have against
                  the user.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  We may at any time at our sole discretion reinstate suspended
                  users.
                </p>

                <p className="description-sm m-t-40 lh-30">
                  Any user that may have been suspended or blocked may not
                  register or attempt to register with the Website or use the
                  Website in any manner whatsoever until such time that such
                  user is reinstated by the Company.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Notwithstanding the above, if you breach the Agreement or the
                  rules and policies and other documents incorporated therein by
                  reference, Hikewise reserves the right to forfeit the money
                  paid by you to us and to take strict legal action including
                  but not limited to referral to the appropriate police or other
                  authorities for initiating criminal or civil or other
                  proceedings against you.
                </p>

                <p className="description-sm m-t-40 lh-30">
                  Hikewise reserves its right to initiate civil and/or criminal
                  proceedings against a user/s, who furnishes invalid/false
                  claim or misleading information to Hikewise.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Any person who, knowingly and with an intent to injure,
                  defraud or deceive Hikewise, files fraudulent information
                  containing false, incomplete, or misleading information shall
                  be guilty of a criminal offence and will be prosecuted to the
                  fullest extent of the law.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Terms and termination of the contract
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  There shall be no contract between Hikewise and the user/s
                  until the services are availed by user/s against
                  consideration.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The Contract against consideration for the services shall be
                  strictly in terms of the services availed and shall end as
                  soon as the services are rendered.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You agree and acknowledge that a violation or breach of any
                  term of this EULA or the misuse of the Website or Service (In
                  Hikewise’s opinion) will result in immediate termination of
                  the services provided to you.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You accept that Hikewise is entitled to terminate your
                  contract at all times, with immediate effect and without
                  giving any prior notice by disabling your use of the Website
                  and the Services you are availing, at its sole discretion.
                  Hikewise is under no obligation to assign any reason.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Defeciency in service
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  During the Service Contract Period, we shall endeavour to
                  maintain commercially acceptable levels of Service
                  availability and ensure that the user is not prevented from
                  making use of the Service as a result of any deficiency or
                  problem in the Network.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  However, User agrees and acknowledges that Hikewise reserves
                  its right to suspend the operation of the website for reasons,
                  including but not limited to updation, repair and technical
                  fault, at its sole discretion. Hikewise is under no obligation
                  to assign any reason for the same.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Service quality, functionality or availability may be affected
                  and the Company shall not be liable for such
                  disruptions/interruptions in any manner including for
                  deficiency of service under the applicable laws, due to but
                  not limited to following reasons;
                </p>
                <ul>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Planned updation/repairs, modifications or maintenance
                      notified to user in advance;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Force Majeure Events;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Any fault in or damage to Service Equipment or Network or
                      components thereof for reasons beyond the reasonable
                      control of the Company;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Any complaint by the User which the Company, after due
                      investigation, finds to be without any basis;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Any order from the state or central government.
                    </p>
                  </li>
                </ul>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise reserves the right to temporarily/ indefinitely
                  suspend or terminate your registration and refuse to provide
                  you with access to all current and future use of the Website
                  at its sole discretion which shall not be termed as deficiency
                  in service in any manner as per law and the user/s hereby
                  expressly waives its right to question in any manner, any such
                  suspension/termination of services by Hikewise.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Indemnity</h2>
                <p className="description-sm m-t-40 lh-30">
                  You confirm that you (alone) shall be responsible and will
                  bear consequences and will defend, indemnify and hold us
                  harmless from any losses, liabilities, damages, costs and
                  expenses, claim or demand, or actions including reasonable
                  attorneys’ fees asserted against or incurred by us, claims
                  made by any third party, caused /arising out of or in
                  connection with wrongful use of the website or its content by
                  you including but not limited to
                </p>
                <ul>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Intellectual property Violations;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Breach of terms &amp; Conditions of EULA or any applicable
                      law or regulation, whether or not referred herein;
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Your violation of any rights of any third party, including
                      with Counsellors/consultants arranged via the Website.
                    </p>
                  </li>
                </ul>
              </div>

              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Liability</h2>
                <p className="description-sm m-t-40 lh-30">
                  The Website, Services and information/recommendations provided
                  to you on or through the Website or otherwise, is for general
                  information purposes only as bonafide guidance and does not
                  constitute any commitment of performance of user in any
                  manner.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise endeavours to provide the utmost quality of the
                  services rendered and shall make every effort to keep the site
                  and its contents correct and up to date. However, User agrees
                  and acknowledges that we make no representations or warranties
                  about the accuracy, reliability, completeness, and/or
                  timeliness of any content, information, text, graphics, links
                  or communications provided on or through the use of the
                  Website or that the operation of the Website will be free of
                  errors, defects, malware and viruses and/or uninterrupted.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise may use the services of third parties to provide
                  information or permit their advertisement on the Website. User
                  accepts hereby that we have no control over this information
                  and we shall not be responsible for or makes no
                  representations or warranties of any nature as to its
                  accuracy, assurances, appropriateness or correctness. The user
                  agrees that such information is provided "as is" and that
                  Hikewise shall not be liable for any losses or damages that
                  may arise from the user's reliance on it, howsoever these may
                  arise.
                </p>
              </div>

              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Limitation of liability
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise will not be liable to you (whether under the law of
                  contract, the law of torts or otherwise) in relation to the
                  contents of, or use of, or otherwise in connection with, this
                  website, for any direct, indirect, incidental, special,
                  consequential or for any business losses, loss of revenue,
                  income, profits or anticipated savings, loss of contracts or
                  business relationships, loss of reputation or goodwill, or
                  loss or corruption of information or data or other intangible
                  losses arising out of or in connection with the website, its
                  services or this agreement (however arising, including
                  negligence).
                </p>
                <p className="description-sm m-t-40 lh-30">
                  These limitations of liability apply even if Hikewise has been
                  expressly advised of the potential loss.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  By using this website, you agree that the exclusions and
                  limitations of liability set out in this agreement are
                  reasonable. If you do not think they are reasonable, you must
                  not use this website and must exit the website.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You accept that, Hikewise has an interest in limiting the
                  personal liability of its officers and employees. You agree
                  that you will not bring any claim personally against
                  Hikewise’s directors, officers, employees, agents, sponsors,
                  consultants, business partners or other representatives
                  ('service providers') in respect of any losses you suffer in
                  connection with the website.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Without prejudice to the foregoing paragraph, you agree that
                  the limitations of warranties and liability set out in this
                  agreement will protect Hikewise’s directors, officers,
                  employees, agents, sponsors, consultants, business partners or
                  other representatives ('service providers') as well as
                  Hikewise.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  If any provision of this agreement is, or is found to be,
                  unenforceable under applicable law, that will not affect the
                  enforceability of the other provisions of this agreement.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Communication policy
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  You are prohibited to engage in direct or indirect
                  communication with counsellors/consultants of Hikewise except
                  for the purposes of the services availed by you.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise intermediate the communication between user/s and the
                  counsellors which shall be limited for the purposes of the
                  services availed and Hikewise shall not be responsible for any
                  communication between the user and the counsellor beyond the
                  scope of the services availed by the user/s in any manner
                  whatsoever.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise intermediate the communication between user/s and the
                  counsellors which shall be limited for the purposes of the
                  services availed and Hikewise shall not be responsible for any
                  communication between the user and the counsellor beyond the
                  scope of the services availed by the user/s in any manner
                  whatsoever.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Violations of policy may result in a range of actions
                  including:
                </p>
                <ul style={{ listStyleType: "circle" }}>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Cancellation of your registration
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Limits on account privileges
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Account suspension
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Compensation for breach of duty
                    </p>
                  </li>
                  <li>
                    <p className="description-sm m-t-40 lh-30">
                      Other proceedings as the law may prescribe
                    </p>
                  </li>
                </ul>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Communication</h2>
                <p className="description-sm m-t-40 lh-30">
                  When you visit https://www.hikewise.com/ or send e-mails to
                  us, you are communicating with us electronically. By
                  communicating with us, you consent to receive communication
                  from us electronically. We will communicate with you by e-mail
                  or by posting notices on our website. You agree that all
                  agreements, notices, disclosures, and other communications
                  that we provide to you electronically, satisfy any legal
                  requirement that such communication be in writing.
                </p>
              </div>

              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Notices</h2>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise may give notice by means of a general notice on the
                  Website, or by electronic mail to your e-mail address on
                  record in Hikewise’s account information, or by written
                  communication sent by regular mail to your address on record
                  in Hikewise’s account information.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You agree that all the agreements, notices, disclosures and
                  other communications that we provide to you electronically
                  shall be deemed adequate service of notice/ electronic record
                  and satisfy any legal requirement that such communication be
                  in writing in terms of the present EULA.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Feedback</h2>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise is always open to the suggestions of the user/s and
                  user/s shall endeavour to suggest improvements and notify
                  Hikewise of any errors or deficiencies, compatibility
                  problems, and other information regarding our website
                  (together, the "Feedback") that may enhance the utility to the
                  user/s for the benefit of user/s as well as Hikewise. However,
                  we are not bound by any such suggestions in any manner
                  whatsoever and incorporating such feedbacks is in our sole
                  discretion.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The parties hereto agree that any feedback or ideas they
                  provide to us regarding any Licensed Technology or any
                  suggested improvements thereto (together, the "Feedback") will
                  be the exclusive property of Hikewise. To the extent the party
                  owns any rights in the Feedback, the party hereby agrees to,
                  and hereby does, assign all right, title and interest in and
                  to the Feedback to Hikewise. The parties hereto agree to
                  perform all acts reasonably requested by Hikewise to perfect
                  and enforce such rights.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Fees</h2>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise shall charge the fee for the services provided as per
                  the structure provided on the website (unless otherwise
                  stated, all fees are quoted in INR). You accept to pay for
                  services, which are subject to payment, as mentioned therein,
                  before using the services, with the payment mechanism
                  associated with them.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  You further undertake not to raise any dispute about the fee
                  charged for the services in any manner whatsoever as you have
                  agreed to the same out of free will and without any undue
                  influence.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise uses third party payments providers to receive
                  payments from user. Hikewise is not responsible for delays or
                  erroneous transactions execution or cancellation of orders due
                  to payment issues. Hikewise takes utmost care to work with
                  third party payment providers, but does not control their
                  systems, processes, technology and work flows, hence cannot be
                  held responsible for any fault at the end of payment
                  providers.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The User agrees and acknowledges that the payment procedure
                  may call for and require additional verification of or
                  information from the User and the User undertakes to provide
                  complete, correct and proper information.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  The fee to be charged by Hikewise from users shall be decided
                  solely by Hikewise and the user/s shall have no right/say to
                  interfere in the same. Fees may vary based on your location
                  and other factors, and Hikewise reserves the right to change
                  any fees at any time at its sole discretion. Any change,
                  update, or modification will be effective immediately upon
                  posting through the relevant Services. Refunds may be
                  available for paid Services as described in our Refund Policy.
                </p>
              </div>

              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Taxes</h2>
                <p className="description-sm m-t-40 lh-30">
                  The user agrees to bear all applicable taxes, charges, cess
                  etc. levied on the services being rendered to the user, as
                  notified by the Central/State Govt. from time to time, unless
                  already included in the price offered.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Refund policy</h2>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise renders services including but not limited to
                  counselling, assessment tests etc., which act as a bonafide
                  guide to the user and the services are rendered as soon as
                  availed, therefore there is no provision for refund of fee
                  paid by the user/s. The user/s is therefore deemed to have
                  understood and accepted that once the fee is paid to Hikewise
                  as per the services availed, there shall be no refund of the
                  said fee.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">
                  Dispute resolution
                </h2>
                <p className="description-sm m-t-40 lh-30">
                  The parties shall attempt that in the event of there being any
                  dispute between them during the use of the website or
                  thereafter, in connection with the validity, interpretation,
                  implementation or alleged breach of any provision of the User
                  Agreement, or the documents they incorporate by reference or
                  anything relating to the present EULA, the dispute is settled
                  by mutual discussion. In the event of failure of discussion,
                  the dispute shall be referred to a sole Arbitrator, who shall
                  be an independent and neutral third party appointed by
                  Hikewise. The place of arbitration shall be Calicut, Kerala,
                  India. The Arbitration proceedings shall be in the English
                  Language and shall be governed by Arbitration &amp;
                  Conciliation Act, 1996 as amended up to date.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Severability</h2>
                <p className="description-sm m-t-40 lh-30">
                  Each of the clauses of this Agreement operates separately. If
                  any Court or any other relevant authority decides that any of
                  them are unlawful or unenforceable, it shall not affect the
                  validity and enforceability of the remaining clauses of the
                  Agreement and they will remain in full force and effect.
                </p>
              </div>

              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Assignment</h2>
                <p className="description-sm m-t-40 lh-30">
                  No rights and obligations under this Agreement shall be
                  assigned by Licensee whether voluntarily or involuntarily or
                  by operation of law, in whole or in part, to any party without
                  the prior written consent of Hikewise, which may be granted or
                  refused at our sole discretion. No such assignment by Licensee
                  howsoever occurring shall relieve the Licensee of its
                  obligations hereunder. Any assignment in violation of this
                  clause shall be null and void from the beginning, and shall be
                  deemed as a material breach of this Agreement.
                </p>
                <p className="description-sm m-t-40 lh-30">
                  Hikewise may transfer its rights and obligations (also known
                  as “assign”) under this Agreement without your prior express
                  consent, provided that such an assignment will be on the same
                  terms or terms that are no less advantageous to you as stated
                  in this Agreement.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Legal advice</h2>
                <p className="description-sm m-t-40 lh-30">
                  You undertake that you had every opportunity to take legal
                  opinion on the present agreement and have understood the legal
                  implications of every clause before agreeing to the same in
                  totality and using the Website.
                </p>
              </div>
              <div className="about-text-wrapper">
                <h2 className="home-section-sub-text m-t-30">Jurisdiction</h2>
                <p className="description-sm m-t-40 lh-30 m-b-160">
                  The parties hereto agree that any matter or issues arising
                  hereunder or any dispute hereunder shall be subject to the
                  exclusive jurisdiction of the courts situated at Calicut,
                  Kerala, India. You undertake not to raise challenge to the
                  jurisdiction clause in any manner and accept the jurisdiction
                  of the Courts at Calicut.
                </p>
              </div>
            </div>
          </div>
        </div>
      </WithPadding>

      <Footer />
    </div>
  );
}
