import style from "./Disclaimer.module.scss";

import Navbar from "components/navbar/Navbar";
import WithPadding from "components/shared/WithPadding";
import Footer from "components/footer/Footer";

export default function Disclaimer() {
  return (
    <div className={style.wrapper}>
      <Navbar background={"white"} />
      <WithPadding>
        <div className={style.title}>Disclaimer</div>

        <p>
          This document is an electronic record in terms of Information
          Technology Act, 2000 ("Act") and made thereunder as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology (Amendment) Act,
          2008. This user agreement is generated by a computer system and does
          not require any physical or digital signatures.
        </p>

        <p>
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries Guidelines) Rules,
          2011 that require publishing the rules and regulations, privacy policy
          and terms and conditions for access and/or usage of www.hikewise.com
          ("Website").
        </p>

        <p>
          vLEAD Eduventures endeavours to provide the utmost quality of the
          services rendered and shall make every effort to keep the site and its
          contents correct and up to date. However, we do not vouch for, or
          guarantee the accuracy, reliability, adequacy, or completeness of any
          data or content and we shall not be liable for any errors, omissions
          or other defects, delays or interruptions in such data, or for any
          actions taken in reliance thereon.
        </p>

        <p>
          We will not be liable to you in relation to the contents of, or use
          of, or otherwise in connection with, this website, for any direct,
          indirect, incidental, special, consequential or for any business
          losses, loss of revenue, income, profits or anticipated savings, loss
          of contracts or business relationships, loss of reputation or
          goodwill, or loss or corruption of information or data or other
          intangible losses arising out of or in connection with the website and
          its services.
        </p>

        <p>
          vLEAD Eduventures provides advice and recommendations based on the
          information received from the user/s and results of the psychometric
          assessments, and is not responsible for the outcome of the assessments
          in any manner.
        </p>

        <p>
          The website, services and information/recommendations provided to you
          on or through the Website or otherwise, is for general information
          purposes only as bonafide guidance and does not constitute any
          commitment of performance of user in any manner.
        </p>

        <p>
          vLEAD Eduventures shall not be responsible for any act/communication
          between the user and the counsellor beyond the scope of the services
          availed by the user/s in any manner whatsoever.
        </p>
      </WithPadding>

      <Footer />
    </div>
  );
}
